- name: install build-essential
  become: True
  apt:
    name: build-essential
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install Keen library
  become: True
  pip:
    name: keen
