- name: install nvm
  tags: bleno
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  args:
    executable: /bin/bash
    creates: "{{ nvm_path }}"

- name: install node with nvm
  tags: bleno
  shell: . {{ nvm_path }} && nvm install --lts
  args:
    executable: /bin/bash






